### ISSUE TITLE
Add post comment route

### ISSUE THREAD

**Issue by 7evam** [7evam/pie-madness-api#1]
The api should be able to add a comment to an existing post. This route should take in a post request at `/posts/{postId}/comments` with the following parameters:

    "postId": <string>, id of the post the comment is being added to
    "comment": <string>, text content of the comment
    "userId": <string>, id of the user
    "secret": <string>, user's secret to confirm their identity
    
    example json input:
    
    "{
    "postId": "9d62953f-99e4-4abd-8f4f-f261cdd49016",
    "comment": "Apple pie is good but there's so much else out there!",
    "userId": "da6404a0-d32c-4e05-8377-319c274c3254",
    "secret": "61b540c8-ddd7-f213-8088-26c645e96eb7"
     }"

    the route should then input the following into the database
    
    PK: POST#<post ID>
    SK: COMMENT#<comment ID>
    text: <comment text>
    timestamp: <unix timestamp of current time>
    user: USER#<user ID>
    
    this route should also
    -generate a unique id for each comment
    -send a 401 unauthorized to any request that doesn't include a secret that matches the secret of the userid
    -send an error message if any of the params above are missing
    -send an error message if the post the comment is being added to does not exist
    -send an error message if the user the comment is being added to does not exist

**Comment by willybeans** [comment]
[here is the pr for this](https://github.com/7evam/pie-madness-api/pull/2)
